team_name = [
 "KF Tiranë",
 "FK Kukësi",
 "KF Skënderbeu",
 "KF Laçi",
 "KF Teuta Durrës",
 "KF Bylis Ballsh",
 "FK Vllaznia",
 "FK Partizani",
 "Luftëtari Gjirokastër",
 "KS Flamurtari Vlorë",
 "Club Brugge KV",
 "KAA Gent",
 "Sporting Charleroi",
 "Royal Antwerp FC",
 "Standard Liège",
 "KV Mechelen",
 "KRC Genk",
 "RSC Anderlecht",
 "Royal Excel Mouscron Péruwelz",
 "SV Zulte Waregem",
 "KV Kortrijk",
 "Sint-Truidense VV",
 "AS Eupen",
 "Cercle Brugge",
 "KV Oostende",
 "Waasland-Beveren",
 "FK Sarajevo",
 "Željezničar Sarajevo",
 "Zrinjski Mostar",
 "Borac Banja Luka",
 "FK Tuzla City",
 "Radnik Bijeljina",
 "Široki Brijeg",
 "Velež Mostar",
 "Sloboda Tuzla",
 "FK Mladost Doboj-Kakanj",
 "Čelik Zenica",
 "Zvijezda 09 Bijeljina",
 "Dinamo Zagreb",
 "HNK Rijeka",
 "Hajduk Split",
 "Lokomotiva Zagreb",
 "NK Osijek",
 "HNK Gorica",
 "Slaven Belupo",
 "NK Istra 1961",
 "NK Inter Zaprešić",
 "NK Varaždin ŠN",
 "Slavia Praha",
 "Viktoria Plzeň",
 "Slovan Liberec",
 "FK Jablonec",
 "Sparta Praha",
 "Baník Ostrava",
 "1. FC Slovácko",
 "České Budějovice",
 "FK Mladá Boleslav",
 "Bohemians 1905",
 "Sigma Olomouc",
 "FK Teplice",
 "FC FASTAV Zlín",
 "MFK Karvina",
 "SFC Opava",
 "1. FK Příbram",
 "FC Midtjylland",
 "FC København",
 "Aarhus GF",
 "Brøndby IF",
 "FC Nordsjælland",
 "Aalborg BK",
 "Randers FC",
 "AC Horsens",
 "Odense BK",
 "Lyngby BK",
 "SønderjyskE",
 "Hobro IK",
 "Esbjerg fB",
 "Silkeborg IF",
 "Liverpool FC",
 "Manchester City",
 "Leicester City",
 "Chelsea FC",
 "Manchester United",
 "Wolverhampton Wanderers",
 "Sheffield United",
 "Tottenham Hotspur",
 "Arsenal FC",
 "Burnley FC",
 "Crystal Palace",
 "Everton FC",
 "Newcastle United",
 "Southampton FC",
 "Brighton & Hove Albion",
 "West Ham United",
 "Watford FC",
 "AFC Bournemouth",
 "Aston Villa",
 "Norwich City",
 "Leeds United",
 "West Bromwich Albion",
 "Fulham FC",
 "Brentford FC",
 "Nottingham Forest",
 "Preston North End",
 "Bristol City",
 "Millwall FC",
 "Cardiff City",
 "Blackburn Rovers",
 "Swansea City",
 "Derby County",
 "Queens Park Rangers",
 "Reading FC",
 "Sheffield Wednesday",
 "Birmingham City",
 "Stoke City",
 "Huddersfield Town",
 "Middlesbrough FC",
 "Wigan Athletic",
 "Hull City",
 "Charlton Athletic",
 "Luton Town",
 "Barnsley FC",
 "Paris Saint-Germain",
 "Olympique Marseille",
 "Stade Rennes",
 "Lille OSC",
 "OGC Nice",
 "Stade Reims",
 "Olympique Lyon",
 "Montpellier HSC",
 "AS Monaco",
 "RC Strasbourg",
 "Angers SCO",
 "Girondins Bordeaux",
 "FC Nantes",
 "Stade Brest",
 "FC Metz",
 "Dijon FCO",
 "AS Saint-Étienne",
 "Nîmes Olympique",
 "Amiens SC",
 "Toulouse FC",
 "Bayern München",
 "Borussia Dortmund",
 "RB Leipzig",
 "Bor. Mönchengladbach",
 "Bayer Leverkusen",
 "VfL Wolfsburg",
 "1899 Hoffenheim",
 "SC Freiburg",
 "Hertha BSC",
 "FC Schalke 04",
 "Eintracht Frankfurt",
 "1. FC Köln",
 "FC Augsburg",
 "1. FC Union Berlin",
 "1. FSV Mainz 05",
 "Fortuna Düsseldorf",
 "Werder Bremen",
 "SC Paderborn 07",
 "Shamrock Rovers",
 "Dundalk FC",
 "Bohemian FC",
 "St Patrick's Athletic",
 "Shelbourne FC",
 "Waterford FC",
 "Derry City",
 "Finn Harps",
 "Cork City",
 "Sligo Rovers",
 "Juventus",
 "Lazio",
 "Inter",
 "Atalanta",
 "AS Roma",
 "SSC Napoli",
 "AC Milan",
 "Hellas Verona",
 "Parma Calcio 1913",
 "Bologna FC",
 "Sassuolo Calcio",
 "Cagliari Calcio",
 "ACF Fiorentina",
 "Udinese Calcio",
 "Torino FC",
 "Sampdoria",
 "Genoa CFC",
 "US Lecce",
 "SPAL 2013 Ferrara",
 "Brescia Calcio",
 "Benevento Calcio",
 "FC Crotone",
 "Frosinone Calcio",
 "Pordenone Calcio",
 "Spezia Calcio",
 "AS Cittadella",
 "US Salernitana 1919",
 "Chievo Verona",
 "Empoli FC",
 "Virtus Entella",
 "AC Pisa",
 "AC Perugia Calcio",
 "SS Juve Stabia",
 "Pescara Calcio",
 "Ascoli Calcio",
 "Venezia FC",
 "US Cremonese",
 "Trapani Calcio",
 "Cosenza Calcio",
 "AS Livorno",
 "Drita Gjilan",
 "KF Ballkani",
 "Prishtina KF",
 "KF Gjilani",
 "KF Feronikeli",
 "KF Llapi",
 "FK Drenica",
 "KF Flamurtari",
 "KF Trepça 89",
 "KF Ferizaj",
 "FC Vushtrria",
 "KF Dukagjini",
 "Floriana FC",
 "Valletta FC",
 "Hibernians FC",
 "Sirens FC",
 "Birkirkara FC",
 "Gżira United",
 "Balzan FC",
 "Mosta FC",
 "Hamrun Spartans",
 "Sliema Wanderers",
 "Gudja United",
 "St. Luċija FC",
 "Senglea Athletics",
 "Tarxien Rainbows",
 "AFC Ajax",
 "AZ Alkmaar",
 "Feyenoord",
 "PSV Eindhoven",
 "Willem II",
 "FC Utrecht",
 "Vitesse",
 "Heracles Almelo",
 "FC Groningen",
 "sc Heerenveen",
 "Sparta Rotterdam",
 "FC Emmen",
 "VVV-Venlo",
 "FC Twente",
 "PEC Zwolle",
 "Fortuna Sittard",
 "ADO Den Haag",
 "RKC Waalwijk",
 "Linfield FC",
 "Coleraine FC",
 "Crusaders FC",
 "Cliftonville FC",
 "Glentoran Belfast",
 "Larne FC",
 "Glenavon FC",
 "Carrick Rangers",
 "Dungannon Swifts",
 "Ballymena United",
 "Warrenpoint Town",
 "Institute FC Drumahoe",
 "Aalesunds FK",
 "FK Bodø/Glimt",
 "FK Haugesund",
 "IK Start",
 "Kristiansund BK",
 "Mjøndalen IF",
 "Molde FK",
 "Odds BK",
 "Rosenborg BK",
 "Sandefjord Fotball",
 "Sarpsborg 08",
 "SK Brann",
 "Stabæk IF",
 "Strømsgodset IF",
 "Vålerenga IF",
 "Viking FK",
 "Legia Warszawa",
 "Piast Gliwice",
 "Pogoń Szczecin",
 "Lech Poznań",
 "Śląsk Wrocław",
 "KS Cracovia",
 "Lechia Gdańsk",
 "Jagiellonia Białystok",
 "Raków Częstochowa",
 "Zagłębie Lubin",
 "Górnik Zabrze",
 "Wisła Płock",
 "Wisła Kraków",
 "Korona Kielce",
 "Arka Gdynia",
 "ŁKS Łódź",
 "SL Benfica",
 "FC Porto",
 "Sporting Braga",
 "Sporting CP",
 "FC Famalicão",
 "Vitória Guimarães",
 "Rio Ave FC",
 "Moreirense FC",
 "CD Santa Clara",
 "Gil Vicente",
 "Boavista",
 "Vitória Setúbal",
 "Os Belenenses",
 "CD Tondela",
 "CS Marítimo",
 "Paços de Ferreira",
 "Portimonense SC",
 "CD Aves",
 "Zenit St. Petersburg",
 "Lokomotiv Moskva",
 "FK Krasnodar",
 "FK Rostov",
 "CSKA Moskva",
 "Dinamo Moskva",
 "Arsenal Tula",
 "Spartak Moskva",
 "FK Ufa",
 "FK Tambov",
 "FC Ural",
 "PFC Sochi",
 "FK Orenburg",
 "Rubin Kazan",
 "Krylia Sovetov",
 "Akhmat Grozny",
 "Celtic FC",
 "Rangers FC",
 "Motherwell FC",
 "Aberdeen FC",
 "Livingston FC",
 "St. Johnstone FC",
 "Hibernian FC",
 "Kilmarnock FC",
 "St. Mirren FC",
 "Ross County FC",
 "Hamilton Academical",
 "Heart of Midlothian",
 "Crvena Zvezda",
 "Partizan",
 "Vojvodina",
 "TSC Bačka Topola",
 "FK Čukarički-Stankom",
 "Radnički Niš",
 "Spartak Subotica",
 "FK Voždovac",
 "Mladost Lučani",
 "Radnik Surdulica",
 "Proleter Novi Sad",
 "FK Napredak",
 "FK Javor",
 "FK Inđija",
 "FK Rad Beograd",
 "FK Mačva Šabac",
 "FC Barcelona",
 "Real Madrid",
 "Sevilla FC",
 "Real Sociedad",
 "Getafe CF",
 "Atlético Madrid",
 "Valencia CF",
 "Villarreal CF",
 "Granada CF",
 "Athletic Bilbao",
 "CA Osasuna",
 "Real Betis",
 "Levante UD",
 "CD Alavés",
 "Real Valladolid",
 "SD Eibar",
 "Celta Vigo",
 "RCD Mallorca",
 "CD Leganés",
 "Espanyol Barcelona",
 "FC St.Gallen",
 "BSC Young Boys",
 "FC Basel",
 "Servette Genève",
 "FC Zürich",
 "FC Luzern",
 "FC Lugano",
 "FC Sion",
 "Neuchâtel Xamax FCS",
 "FC Thun",
 "Trabzonspor",
 "İstanbul Başakşehir F.K.",
 "Galatasaray",
 "Sivasspor",
 "Beşiktaş",
 "Alanyaspor",
 "Fenerbahçe",
 "Göztepe",
 "Gazişehir Gaziantep FK",
 "Denizlispor",
 "Antalyaspor",
 "Gençlerbirliği",
 "Kasımpaşa SK",
 "Atiker Konyaspor",
 "Yeni Malatyaspor",
 "Çaykur Rizespor",
 "MKE Ankaragücü",
 "Kayserispor",
 "Connah's Quay Nomads",
 "The New Saints",
 "Bala Town",
 "Barry Town United",
 "Caernarfon Town",
 "Newtown AFC",
 "Shakhtar Donetsk",
 "Dinamo Kiev",
 "Zorya Lugansk",
 "Desna Chernigov",
 "FC Oleksandriya",
 "Kolos Kovalivka",
 "Boca Juniors",
 "River Plate",
 "Vélez Sarsfield",
 "Racing Club",
 "Argentinos Juniors",
 "Defensa y Justicia",
 "Lanús",
 "San Lorenzo",
 "Rosario Central",
 "Newell's Old Boys",
 "Arsenal de Sarandí",
 "Talleres de Córdoba",
 "Estudiantes",
 "Independiente",
 "Atlético Tucumán",
 "Unión de Santa Fe",
 "Banfield",
 "Central Córdoba SdE",
 "Gimnasia de La Plata",
 "Patronato de Paraná",
 "Huracán",
 "Aldosivi",
 "Colón de Santa Fe",
 "Godoy Cruz",
 "Athletico Paranaense",
 "Atlético Goianiense",
 "Atlético Mineiro",
 "Bahia - BA",
 "Botafogo - RJ",
 "Ceará - CE",
 "Corinthians SP",
 "Coritiba FC",
 "Flamengo RJ",
 "Fluminense RJ",
 "Fortaleza",
 "Goiás",
 "Grêmio Porto Alegre",
 "Internacional",
 "Palmeiras",
 "Red Bull Bragantino",
 "Santos FC",
 "São Paulo FC",
 "Sport - PE",
 "Vasco da Gama",
 "Universidad Católica",
 "Unión La Calera",
 "Curicó Unido",
 "Universidad de Chile",
 "Antofagasta",
 "Palestino",
 "Unión Española",
 "Audax Italiano",
 "Huachipato",
 "Everton",
 "Cobresal",
 "Iquique",
 "Colo-Colo",
 "Universidad de Concepción",
 "La Serena",
 "O'Higgins",
 "Coquimbo Unido",
 "Santiago Wanderers",
 "Atlético Nacional",
 "Deportivo Pasto",
 "Santa Fe",
 "Deportes Tolima",
 "Alianza Petrolera",
 "Atlético Junior",
 "Once Caldas",
 "América de Cali",
 "Deportivo Cali",
 "Deportivo Pereira",
 "Independiente Medellín",
 "Rionegro Águilas Doradas",
 "La Equidad",
 "Envigado FC",
 "Atlético Bucaramanga",
 "Jaguares de Córdoba",
 "Millonarios",
 "Cúcuta Deportivo",
 "Boyacá Chicó",
 "Patriotas FC",
 "Rentistas",
 "Progreso",
 "Cerro Largo",
 "Defensor Sporting",
 "Liverpool",
 "Montevideo Wanderers",
 "Torque",
 "Boston River",
 "Peñarol",
 "River Plate",
 "Plaza Colonia",
 "Cerro",
 "Fénix",
 "Nacional",
 "Danubio",
 "Deportivo Maldonado",
 "CR Bélouizdad",
 "ES Sétif",
 "MC Alger",
 "JS Kabylie",
 "CS Constantine",
 "JS Saoura",
 "AS Aïn M'lila",
 "MC Oran",
 "USM Alger",
 "Paradou AC",
 "USM Bel Abbes",
 "ASO Chlef",
 "CA Bordj Bou Arreridj",
 "US Biskra",
 "NA Hussein Dey",
 "NC Magra",
 "Al-Ahly",
 "Al-Mokawloon",
 "Pyramids FC",
 "Zamalek",
 "Ittihad El-Iskandary",
 "Smouha Sporting Club",
 "ENPPI",
 "El-Entag El-Harby",
 "Ismaily",
 "Al-Masry Club",
 "El Gouna",
 "Haras El Hodood",
 "Aswan",
 "Tala'ea El-Gaish SC",
 "Tanta",
 "Wadi Degla FC",
 "Misr lel-Maqasah SC",
 "FC Masr",
 "Espérance de Tunis",
 "Club Sportif Sfaxien",
 "US Monastir",
 "Club Africain",
 "Stade Tunisien",
 "Étoile du Sahel",
 "US Ben Guerdane",
 "AS Slimane",
 "CS Chebba",
 "US Tataouine",
 "CS Hammam-Lif",
 "JS Kairouan",
 "CA Bizertin",
 "ES Métlaoui",
 "Atlético Ottawa",
 "Cavalry FC",
 "FC Edmonton",
 "Forge FC",
 "HFX Wanderers",
 "Pacific FC",
 "Valour FC",
 "York9 FC",
 "Cruz Azul",
 "Club León",
 "Santos Laguna",
 "CF América",
 "Deportivo Guadalajara",
 "Pumas UNAM",
 "UANL Tigres",
 "FC Juárez",
 "Monarcas Morelia",
 "Puebla FC",
 "CF Pachuca",
 "Gallos Blancos",
 "Atlético San Luis",
 "Club Necaxa",
 "Deportivo Toluca",
 "Club Tijuana",
 "Atlas Guadalajara",
 "CF Monterrey",
 "Atlanta United FC",
 "Sporting Kansas City",
 "Minnesota United FC",
 "Colorado Rapids",
 "FC Dallas",
 "Los Angeles FC",
 "Seattle Sounders",
 "Portland Timbers",
 "Vancouver Whitecaps",
 "Real Salt Lake",
 "Los Angeles Galaxy",
 "San Jose Earthquakes",
 "Houston Dynamo",
 "Impact de Montréal",
 "New York RB",
 "Toronto FC",
 "Columbus Crew",
 "D.C. United",
 "Chicago Fire",
 "New England Revolution",
 "Orlando City",
 "Philadelphia Union",
 "FC Cincinnati",
 "Inter Miami CF",
 "New York City FC",
 "Sydney FC",
 "Melbourne City FC",
 "Wellington Phoenix",
 "Brisbane Roar",
 "Perth Glory",
 "Western United FC",
 "Adelaide United",
 "Western Sydney Wanderers",
 "Newcastle United Jets",
 "Melbourne Victory",
 "Central Coast Mariners",
 "Beijing Guoan",
 "Chongqing Lifan",
 "Dalian Pro",
 "Guangzhou Evergrande",
 "Guangzhou R&F",
 "Hebei China Fortune FC",
 "Henan Jianye",
 "Jiāngsū Sūníng",
 "Qingdao Huanghai",
 "Shandong Luneng",
 "Shanghai Shenhua",
 "Shanghai SIPG",
 "Shenzhen FC",
 "Shijiazhuang Ever Bright",
 "Tianjin Teda",
 "Wuhan Zall FC",
 "Mohun Bagan",
 "East Bengal FC",
 "Minerva Punjab FC",
 "Real Kashmir",
 "TRAU FC",
 "Gokulam Kerala",
 "Chennai City FC",
 "Churchill Brothers",
 "NEROCA FC",
 "Aizawl FC",
 "ATK (India)",
 "Bengaluru FC",
 "Chennaiyin FC",
 "Mumbai City FC",
 "Odisha FC",
 "Kerala Blasters FC",
 "Jamshedpur",
 "NorthEast United FC",
 "Hyderabad FC",
 "Indian Arrows",
 "Persib Bandung",
 "Bali United",
 "Pusamania Borneo",
 "Persipura Jayapura",
 "PSIS Semarang",
 "PSM Makassar",
 "Persiraja Banda Aceh",
 "Madura United FC",
 "Persija Jakarta",
 "TIRA-Persikabo",
 "Bhayangkara FC",
 "Arema Cronus FC",
 "Persik Kediri",
 "Persita Tangerang",
 "Persebaya Surabaya",
 "PSS Sleman",
 "PS Barito Putera",
 "Persela Lamongan",
 "Persepolis",
 "Sepahan FC",
 "Tractor Sazi",
 "Esteghlal",
 "Shahr Khodro FC",
 "Foolad FC",
 "Sanat Naft FC",
 "Naft Masjed Soleyman",
 "Machine Sazi",
 "Nassaji Mazandaran",
 "FC Zob Ahan",
 "Pars Jonoubi Jam",
 "Gol Gohar FC",
 "Saipa FC",
 "Shahin Bushehr FC",
 "Paykan FC",
 "Sanfrecce Hiroshima",
 "Kashiwa Reysol",
 "FC Tokyo",
 "Urawa Red Diamonds",
 "Gamba Osaka",
 "Cerezo Osaka",
 "Nagoya Grampus",
 "Vegalta Sendai",
 "Vissel Kobe",
 "Yokohama FC",
 "Kawasaki Frontale",
 "Sagan Tosu",
 "Shonan Bellmare",
 "Yokohama F. Marinos",
 "Oita Trinita",
 "Consadole Sapporo",
 "Shimizu S-Pulse",
 "Kashima Antlers",
 "Al Duhail SC",
 "Al Rayyan",
 "Al Sadd",
 "Al Gharafa",
 "Al Arabi",
 "Al Sailiya",
 "Al Wakrah",
 "Al Ahli Doha",
 "Qatar SC",
 "Al Khor SC",
 "Umm-Salal",
 "Al Shahaniya",
 "Al Hilal",
 "Al Nassr",
 "Al Wehda",
 "Al Ahli SFC",
 "Al Faisaly",
 "Al Taawoun",
 "Al Ra’ed",
 "Al Shabab",
 "Abha Club",
 "Al Ettifaq",
 "Al Fayha",
 "Al Hazem",
 "Al Ittihad",
 "Al Fateh",
 "Damac FC",
 "Al Adalah",
 "Shabab Al Ahli Club",
 "Al Ain FC",
 "Al Jazira Club",
 "Sharjah FC",
 "Al Wahda",
 "Al Nasr SC",
 "Al Dhafra",
 "Al Wasl",
 "Baniyas SC",
 "Ajman Club",
 "Ittihad Kalba SCC",
 "Khor Fakkan Club",
 "Hatta Club",
 "Al Fujairah"
 ]